axonivy-market/market

- market/genderize/meta.json
- market/uipath/meta.json
- Allow multiple installers
- Beauty structure for rest features and properties
> XIVY-5003 Improve 'meta.json' structure

- Jenkinsfile
- market-test/.classpath
- market-test/pom.xml
- market-test/src/main/java/com/axonivy/market/CreateBundle.java
- market-test/src/test/java/com/axonivy/market/test/ValidateRepoTest.java
- market/basic-workflow-ui/meta.json
- market/demos/meta.json
- market/doc-factory/meta.json
- market/genderize/meta.json
- market/portal/meta.json
- market/uipath/meta.json
- market/visualvm-plugin/meta.json
Every product needs now to have an id. This id is they
identifier for the product on the website. We we want
to have stable links and want restructure the hole repository
here at anytime. The id must be unique over all products.
> XIVY-5003 Make repository structure independent of dev website

- market/uipath/meta.json
... re-use from the ivy-core and configure it, rather re-implementing an object mapper in code
> use new JsonFeature properties

- README.md
- doc/contribute.md
so that first connector providers can get involved
> initiate contributing docs

- market/connector/microsoft365/demo/msGraphDemo/dataclasses/ms/graph/demo/ToDoDemo.ivyClass
- market/connector/microsoft365/demo/msGraphDemo/pom.xml
- market/connector/microsoft365/demo/msGraphDemo/processes/Demo/ms365ToDo.mod
- market/connector/microsoft365/demo/msGraphDemo/restClients.restConfig
- market/connector/microsoft365/demo/msGraphDemo/src/com/microsoft/auth/OAuth2Feature.java
- market/connector/microsoft365/demo/msGraphDemoTest/src/com/microsoft/graph/GraphServiceMock.java
- market/connector/microsoft365/demo/msGraphDemoTest/src/com/microsoft/graph/json/toDoLists.json
- market/connector/microsoft365/demo/msGraphDemoTest/src/com/microsoft/graph/json/toDoTasks.json
- market/connector/microsoft365/demo/msGraphDemoTest/src_test/com/microsoft/graph/TestToDoDemo.java
- market/connector/microsoft365/meta.json
- show how easy tasks from outlook could be used in workflow processes.
> XIVY-5006 demo: read/write outlook ToDo list

- market/connector/docusign/demo/eSignatureDemoTest/src_test/net/docusign/test/TestJwtBuilder.java
To be merged after this change is gone through review and available in the nightly build:
https://bitbucket.org/axonivy-prod/ivy-core/pull-requests/3121/xivy-5184-provide-a-simpler-interface-for/diff
> XIVY-5184 refactor: benefit of simpler FeatureConfig interface

- market/connector/docusign/demo/eSignatureDemo/.classpath
- market/connector/docusign/demo/eSignatureDemo/.gitignore
- market/connector/docusign/demo/eSignatureDemo/pom.xml
- market/connector/genderize/demo/genderizeIoDemo/.classpath
- market/connector/genderize/demo/genderizeIoDemo/.gitignore
- market/connector/microsoft365/demo/msGraphDemo/.gitignore
- market/connector/microsoft365/demo/msGraphDemo/pom.xml
- market/connector/twitter/demo/twitterDemo/.classpath
- market/connector/twitter/demo/twitterDemo/.gitignore
- market/connector/twitter/demo/twitterDemo/pom.xml
- market/connector/uipath/demo/uiPathDemo/.classpath
- market/connector/uipath/demo/uiPathDemo/.gitignore
- market/connector/uipath/demo/uiPathDemo/pom.xml
from lib_generated/client to lib/generated/rest
> XIVY-4975 move rest client libs

- market/connector/microsoft365/demo/msGraphDemo/.classpath
> fix ms connector classpath

- market/connector/microsoft365/demo/msGraphDemo/processes/Demo/ms365Calendar.mod
- market/connector/microsoft365/demo/msGraphDemo/processes/Demo/ms365Mail.mod
I've written a story for this problem. I think we will face it for every major update of the ms-graph APIs.
https://jira.axonivy.com/jira/browse/XIVY-5573
> Adapt demo to new OpenAPI release of ms.graph

- market/connector/docusign/demo/eSignatureDemo/processes/Demo/eSign.mod
- market/connector/docusign/demo/eSignatureDemo/restClients.restConfig
- market/connector/docusign/meta.json
- rather than re-declaring it on each and every RestClientCall activity.
> XIVY-5214 inject 'accountId' from restClientConfig

- market/connector/uipath/demo/uiPathDemo/pom.xml
- market/connector/uipath/meta.json
v11 API is no longer public accessible
> migrate to UiPATH v12 API

- market/connector/microsoft365/msgraph/demo/msGraphDemo/processes/Connector/msCalendar.mod
- market/connector/microsoft365/msgraph/demo/msGraphDemo/processes/Connector/msMail.mod
- market/connector/microsoft365/msgraph/demo/msGraphDemo/processes/Connector/msToDo.mod
- market/connector/uipath/demo/uiPathDemo/processes/RPA/uiPathRpa.mod
- Add CONNECTOR tag to all callable sub starts
- Add a description on every callable sub process, sub start element,
sub start call and return parameter
> XIVY-5538 Add CONNECTOR tag and descriptions to sub starts

- market/utils/google-maps-api/google-geo-api-demo/src_hd/com/google/map/Viewer/ViewerProcess.mod
- fix false positiv validation error after install
> simplify API.key warning

- market/connector/docusign/meta.json
> Change docusign tag to e-signature

- market/connector/a-trust/meta.json
> Revert "Temporary unlist atrust connector"

- market/connector/microsoft365/msgraph/demo/msGraphDemo/processes/Connector/msCalendar.mod
- market/connector/microsoft365/msgraph/demo/msGraphDemo/processes/Connector/msMail.mod
- do not merge before releasing 9.2.1
> XIVY-5573 use body names containing path parts (9.2.1 only!)

- market/connector/sftp/README.md
and less emphasize on the rebex server product notes
> fix readme links

- market/connector/twitter/demo/twitterDemo/pom.xml
- introduce from 2.26 to version 2.27
- see https://github.com/SnowCait/twitter-swagger-ui/commit/025f8194b91107f043e59729319724383042232b#diff-3c8f271765f48e0e105075ee85cc6d33d0376e8495398663dab2a39c5f315f44
> ignore compile errors with twitter api

- market/connector/uipath/demo/uiPathDemo/processes/RPA/uiPathRpa.mod
- due to other new resource using the same name
> fix UI path: param type changed

- market/connector/currencyConverter/demo/currencyConverter/pom.xml
- market/connector/docusign/demo/eSignatureDemo/pom.xml
- market/connector/docusign/demo/eSignatureDemoTest/pom.xml
- market/connector/genderize/demo/genderizeIoDemo/pom.xml
- market/connector/jira/demo/jiraDemo/pom.xml
- market/connector/microsoft365/msgraph/demo/msGraphDemo/pom.xml
- market/connector/microsoft365/msgraph/demo/msGraphDemoTest/pom.xml
- market/connector/twitter/demo/twitterDemo/pom.xml
- market/connector/twitter/demo/twitterDemoTest/pom.xml
- market/connector/uipath/demo/uiPathDemo/pom.xml
- market/connector/uipath/demo/uiPathDemoTest/pom.xml
> Revert "Raise project build plugin version to 9.3.1"

- raise-build-plugin-version.sh
I think this is also not needed anymore as we removed that pom.xml
> Remove not needed version raise script

- .github/ISSUE_TEMPLATE/onboard-to-market.md
- .github/ISSUE_TEMPLATE/product-idea.md
as discusses on last scrum-of-scrum meeting:
an new issue template, to describe ideas on future market-products and their capabilities.
> XIVY-10481 product idea as template

- market/portal/meta.json
Changed from bitbutket to github
Hi @ivy-lmu , could you help to review and merge it.
Thanks!
> Corrected the portal source code

- .github/ISSUE_TEMPLATE/onboard-to-market.md
- .github/ISSUE_TEMPLATE/product-idea.md
just registered you as standard reviewer @ivy-sgi  for new Market issues.
... feel free to polish these issue templates for you needs, so that upcoming issues may be handled more effectively
> add Sabine as standard assignee for new issues

- market-test/pom.xml
- market-test/src/main/java/com/axonivy/market/MarketMetaSchema.java
> MARP-234 can not find old artifacts after changing product name

- market-test/pom.xml
- market-test/src/main/java/com/axonivy/market/MarketMetaSchema.java
Hi @ivy-rew 
We are implementing the feature to support multilingualism for the landing page on the new marketplace's website.
We want to introduce two new fields such as names, and descriptions to display the translated text.
E.g for the description of the Axon Ivy portal
Can you help me review this pull request and give me your feedback?
> MARP-560 Introduce new fields - names and descriptions- support multilingualism

- market/connector/a-trust/meta.json
Wait for refactoring SOAP->REST to list it again on the website.
> "listed": false,

- market/demos/aspose-barcode/meta.json
- market/demos/aspose-email/meta.json
- market/demos/master-detail/meta.json
This PR adds missing Maven artifact blocks to all `meta.json` files in the repository.
> Add missing Maven artifact blocks

- Jenkinsfile
I'm resurrecting the market-json-schema publishing flow:
- it's still in use and needs an update #495
> drop market.tar publishing

- market/utils/portal/meta.json
Introduce portal component in selection dropdown
> MARP-2320 It is not possible to download portal as zip file
